Missioncontrol addbasestationstates
TrickfireRobotics/mission-control pull request #44
Opened 2024-12-25 00:27 UTC by Quashnock

Summary
Over the past couple days I tried working on this issue a bit on the new addbasestationstates branch. As it currently stands I have implemented the necessary UI and created a store for the base station operation states specified above, however I am not certain if the topic publishing works. I intend to add the spacebar hotkey disable in the future. I would appreciate feedback on the UI and implementation, particularly if the topic publishing works and if the newly added store is factored well.

UI
I chose to implement the select as a dropdown selector in the NavBar, due to the fact that only one can be selected at a time and I view the operation mode as an important piece of information to be able to view and switch on any screen, especially in emergency circumstances when the rover needs to be quickly disabled. Adding this extended the states section so that the page selection section could run out of space, so I set it so the page selection section grows to whatever length it has and can scroll horizontally for more space. I am considering a better way to communicate this visually.

Implementation
I chose to add a slice of the store for the operation state because it may be valuable for other components to know the current operation state, and with my current implementation the value of the operationState should be the single source of truth for what state the base station is currently in. However, I did run into an issue with importing the OperationState type from the store into the NavBar as I was receiving an error that the import could not recognize my type export. I am not too familar with TypeScript or Vue, so from what I was able to gather this may be an issue with a TSconfig we have. I have currently redefined the type in NavBar to make it function, and while I recognize this is not best practice it may not be too big of an issue to just keep around. Finally, I created a topic called "/setOperationState" that store publishes to everytime the state updates with a string containing the state to update to. I am not certain at this time if it functions as intended or if it works well with the backend robot code.

Thank you for reading and let me know if you have any questions or feedback!

2024-12-31 08:13 UTC, adamseth2 requested changes
Confirmed it is publishing the message correctly!
![image](https://github.com/user-attachments/assets/d5d8a30b-c2d2-4dbb-b140-e70dc5d7a6f4)

The only thing I see is that the operation status is not distinct enough as its probably very important to see it at a glimpse on the status of the rover (hard to tell just by text, so color = good tldr). I suggest making it a whole different color like red for stop, purple for auto and green for tele mode.

The styles for option are good though! I would suggest moving the current option styles for the operationstate to become global scss to become what it should look by default and then modify this option more manually. If possible, it probably look best if it took up the whole width of the navbar or most of it too.

2024-12-31 08:24 UTC, adamseth2 commented
Good work though! and I would not worry about the space bar as I believe @uellenberg  is working on that for the controller/keyboard. But thanks for thinking ahead because yeah I think there potentially could be a problem with the UI state not matching up with the rover. I believe you can do this with option tags but make it so that the value of the option tag is binded by  the operationState from the store (similar example in exampleComponent.vue for input tags). This would allow if the store value changes from like a keyboard/controller input, it would be as simple as changing the store value to update the navbar state too. Lmk if that doesn't make sense

2024-12-31 21:19 UTC, Quashnock commented on package.json
> +    "lint": "^0.8.19",
Yes, I thought I also needed to install lint. I'll remove it in the updated commit.

2024-12-31 21:23 UTC, Quashnock commented on src/components/Navbar.vue
> +      border: 5px solid hsl(240, 20%, 15%) !important;
You're right! I must have left it behind from messing around with the border, thanks for catching that!

2024-12-31 21:31 UTC, Quashnock commented on src/components/Navbar.vue
> +type OperationState = 'disabled' | 'teleoperation' | 'autonomous';
This change works! Thanks for the help, I am still trying to get familar with some typescript syntax.

2025-01-01 00:24 UTC, adamseth2 commented on src/components/Navbar.vue
> +type OperationState = 'disabled' | 'teleoperation' | 'autonomous';
all good yeah this stumped me for the longest time too when I first used it

2025-01-01 04:54 UTC, uellenberg commented on package.json
> +    "lint": "^0.8.19",
@Quashnock Looks like package-lock.json got modified, but package.json didn't. In general, package-lock.json shouldn't be modified manually. You can run `git checkout master -- package.json` and `git checkout master -- package-lock.json` in order to reset these files back to their original versions, then commit those new (old) files.

2025-01-01 04:57 UTC, uellenberg commented on src/store/operationStateStore.ts
> +  function setOperationState(state: OperationState) {
Looks like state is never used, which might cause problems later since the function says that it is used. By the way, to write a function's description so that it works nicely with IDEs, you can write it as `/** This function does ... */`.

2025-01-01 05:03 UTC, uellenberg commented on src/assets/global.css.map
What created this file? It looks like a compile-time artifact that shouldn't be included in the repo, but I'm not sure.

2025-01-01 17:46 UTC, adamseth2 commented on src/assets/global.css.map
hm nice catch! this is most likely the vscode scss watcher when working with vanilla scss, but vue automatically compiles it for us, so yeah should be deleted along with global.css

2025-01-01 23:54 UTC, Quashnock commented on src/store/operationStateStore.ts
> +  function setOperationState(state: OperationState) {
I use operationState's value property to hold the current operation state of the robot. I am new to vue so I am not sure if this is the proper use, but it is how I saw it used in controllerStore.ts. I'll rewrite the function description in the next commit.

2025-01-02 00:08 UTC, adamseth2 commented on src/store/operationStateStore.ts
> +  function setOperationState(state: OperationState) {
Weird, when testing it looked fine, but yeah line 16 should be: 
`operationState.value = state`
Because right now it just sets it to autonomous from what I can tell

2025-01-02 00:24 UTC, Quashnock commented on src/assets/global.css.map
Alright! I deleted the specified file and global.css in the latest commit.

2025-01-02 00:45 UTC, Quashnock commented
Hi Adam and Jonah! I just made a commit that made all the changes and fixes you specified with your comments. 

Additionally, I swapped the dropdown menu for a set of buttons since I couldn't find a way to get the dropdown menu to display the correct state if it is changed elsewhere. I also think this reads better and lets users swap modes quicker. The correct button should always be highlighted with the specified color in coordination with the operation state held in the store. This way you can use the state setter in other parts of mission control and the buttons should highlight accordingly.

Thanks for your pointers and let me know if you have any other questions for me!

2025-01-02 05:10 UTC, adamseth2 commented on src/store/operationStateStore.ts
> +  function setOperationState(state: OperationState) {
Also yeah interesting didn't know you needed to use javadoc style for your ide to pick up the comment. Good to know for the future and to try to enforce

2025-01-02 05:16 UTC, adamseth2 commented
Looks great! Love the button groups and agree they look nicer!

Just a couple of small things:
1. Rather than "Off", name it "Disable" because I think it can be confusing what "off" means because Im 99% sure we just want the motors to completely turn off and not all other systems like GPI and cameras.
2. Though github workflow says successfully passed the test (a little annoying that github does that), when you open it up, it shows 3 lint issues. Though small, fixing them will ensure the lint checker only gives warnings for new PRs
![image](https://github.com/user-attachments/assets/8a8e235e-6dca-4245-88fb-00b96e418de5)

3.  Run these commands in the terminal to reset the package .jsons back to the master branch because it doesn't seem like the changes are needed
```
git checkout origin/master -- package.json 
git checkout origin/master -- package-lock.json
```

2025-01-03 22:02 UTC, uellenberg approved these changes
I want to make sure everything gets synchronized correctly, but we can do that at a later date. Right now, it looks like operation state is set to disabled by default, but that isn't synchronized by the rover. If we reload the page, the operation mode will say disabled, even though the rover might be in autonomous mode, which could be confusing.

For now though, great work, and thanks for putting up with all our nitpicks 😆

2025-01-03 22:12 UTC, adamseth2 commented
> I want to make sure everything gets synchronized correctly, but we can do that at a later date. Right now, it looks like operation state is set to disabled by default, but that isn't synchronized by the rover. If we reload the page, the operation mode will say disabled, even though the rover might be in autonomous mode, which could be confusing.
> 
> For now though, great work, and thanks for putting up with all our nitpicks 😆

Yeah I realized when looking at the logic also that this is a fundamental problem overall with the mission control. There are a couple of ways to fix it, but I have to think about it more. Today or tomorrow I'll write a message of ideas to fix it, so we can figure what the best method. But yep for now, good work 🤘

2025-01-03 23:54 UTC, adamseth2 commented on src/components/Navbar.vue
> +      button#teleoperation-button.checked {
My bad for not noticing this earlier, but let's use the power of scss to make this even cleaner.

Basically instead of repeating the word button, just use `&`
```scss
button {
        height: 80%;
        cursor: pointer;
        align-items: center;
        padding: 0 1rem;
        border-radius: 4px;
        background-color: transparent;
        color: white;
      }
      &:hover:not(.checked) {
      ...
      }
      &disabled-button.checked {
      ...
      }
}
...
```

2025-01-04 00:00 UTC, adamseth2 approved these changes
Thanks again for your hard work! Other than that extremely small thing, looks good and it is ready to merge

2025-01-04 00:38 UTC, merged

2025-01-04 00:49 UTC, Quashnock commented
I've made the final changes and merged the branch with master. Since we still have the issue with the operation state desynchronizing with the rover when the page reloads I will keep the branch and GitHub issue open for now. Thanks for all of your help and feeback throughout this process, I'm glad we ran into some common issues now so that future work can go even smoother!

2025-01-04 00:53 UTC, adamseth2 commented
> I've made the final changes and merged the branch with master. Since we still have the issue with the operation state desynchronizing with the rover when the page reloads I will keep the branch and GitHub issue open for now. Thanks for all of your help and feeback throughout this process, I'm glad we ran into some common issues now so that future work can go even smoother!

Congrats on the first PR!  And yeah FYI the desynchronizing issue is not just with yours but also stuff like the arm mode, but glad we noticed it now